package com.example.demo.mapper;

import com.example.demo.dao.Menu;
import com.example.demo.dao.MenuCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int countByExample(MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int deleteByExample(MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    List<Menu> selectByExampleWithRowbounds(MenuCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    List<Menu> selectByExample(MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    Menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByPrimaryKey(Menu record);
}