package com.example.demo.mapper;

import com.example.demo.dao.Student;
import com.example.demo.dao.StudentCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int countByExample(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int deleteByExample(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    List<Student> selectByExampleWithRowbounds(StudentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    List<Student> selectByExample(StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_student
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByPrimaryKey(Student record);
}