package com.example.demo.mapper;

import com.example.demo.dao.Wallet;
import com.example.demo.dao.WalletCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface WalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int countByExample(WalletCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int deleteByExample(WalletCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    List<Wallet> selectByExampleWithRowbounds(WalletCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    List<Wallet> selectByExample(WalletCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    Wallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Wallet record, @Param("example") WalletCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByExample(@Param("record") Wallet record, @Param("example") WalletCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    int updateByPrimaryKey(Wallet record);
}