package com.example.demo.dao;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Menu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_menu.Id
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_menu.MenuName
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_menu.Price
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_menu.Count
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_menu.Createtime
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_menu.LastUpdateDate
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_menu.Id
     *
     * @return the value of t_dining_menu.Id
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_menu.Id
     *
     * @param id the value for t_dining_menu.Id
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_menu.MenuName
     *
     * @return the value of t_dining_menu.MenuName
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_menu.MenuName
     *
     * @param menuName the value for t_dining_menu.MenuName
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_menu.Price
     *
     * @return the value of t_dining_menu.Price
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_menu.Price
     *
     * @param price the value for t_dining_menu.Price
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_menu.Count
     *
     * @return the value of t_dining_menu.Count
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_menu.Count
     *
     * @param count the value for t_dining_menu.Count
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_menu.Createtime
     *
     * @return the value of t_dining_menu.Createtime
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_menu.Createtime
     *
     * @param createtime the value for t_dining_menu.Createtime
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_menu.LastUpdateDate
     *
     * @return the value of t_dining_menu.LastUpdateDate
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_menu.LastUpdateDate
     *
     * @param lastUpdateDate the value for t_dining_menu.LastUpdateDate
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_menu
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menuName=").append(menuName);
        sb.append(", price=").append(price);
        sb.append(", count=").append(count);
        sb.append(", createtime=").append(createtime);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append("]");
        return sb.toString();
    }
}