package com.example.demo.dao;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Wallet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_wallet.Id
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_wallet.StudentId
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_wallet.Amount
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_wallet.Createtime
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dining_wallet.LastUpdateDate
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_wallet.Id
     *
     * @return the value of t_dining_wallet.Id
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_wallet.Id
     *
     * @param id the value for t_dining_wallet.Id
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_wallet.StudentId
     *
     * @return the value of t_dining_wallet.StudentId
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_wallet.StudentId
     *
     * @param studentId the value for t_dining_wallet.StudentId
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_wallet.Amount
     *
     * @return the value of t_dining_wallet.Amount
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_wallet.Amount
     *
     * @param amount the value for t_dining_wallet.Amount
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_wallet.Createtime
     *
     * @return the value of t_dining_wallet.Createtime
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_wallet.Createtime
     *
     * @param createtime the value for t_dining_wallet.Createtime
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dining_wallet.LastUpdateDate
     *
     * @return the value of t_dining_wallet.LastUpdateDate
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dining_wallet.LastUpdateDate
     *
     * @param lastUpdateDate the value for t_dining_wallet.LastUpdateDate
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dining_wallet
     *
     * @mbggenerated Fri Mar 30 10:34:20 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", amount=").append(amount);
        sb.append(", createtime=").append(createtime);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append("]");
        return sb.toString();
    }
}